apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: webserver-cheerp-cert
  namespace: default
spec:
  secretName: webserver-cheerp-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: cheerp.cppse.nl
  dnsNames:
  - cheerp.cppse.nl
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - cheerp.cppse.nl
    - http01:
        ingress: my-ingress
      domains:
      - cheerp.cppse.nl

